### ISSUE TITLE
Find a sample BIDS dataset which we can use for part 2

### ISSUE THREAD

**Issue by anthonycrane** [anthonycrane/psc290-fmriprep#5]

**Comment by anthonycrane** [comment]
@sjbeard @rm1279 test

**Comment by rm1279** [comment]
@anthonycrane @sjbeard Here are a few datasets to check out. It isn't really a big deal which one we pick, but I figure providing a few options wouldn't hurt.
https://openneuro.org/datasets/ds000109/versions/00001
https://openneuro.org/datasets/ds000119/versions/00001
https://openneuro.org/datasets/ds000213/versions/00002

**Comment by rm1279** [comment]
https://openneuro.org/datasets/ds000214/versions/00001

**Comment by rm1279** [comment]
@anthonycrane @sjbeard 
Cyberball
https://openneuro.org/datasets/ds000214/versions/00001
